"""order item dish fk

Revision ID: 5e67a13b4d80
Revises: 86919bd82f86
Create Date: 2025-11-03 23:59:59.743432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e67a13b4d80'
down_revision: Union[str, Sequence[str], None] = '86919bd82f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order_items', 'dishes', ['dish_id'], ['dish_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    # ### end Alembic commands ###
