"""order item fk

Revision ID: 6e240257e7cb
Revises: ea5c893ce7b5
Create Date: 2025-11-03 21:52:53.591902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e240257e7cb'
down_revision: Union[str, Sequence[str], None] = 'ea5c893ce7b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    # ### end Alembic commands ###
