"""order remove currency

Revision ID: 86919bd82f86
Revises: bd839c4093b3
Create Date: 2025-11-03 23:39:51.689147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86919bd82f86'
down_revision: Union[str, Sequence[str], None] = 'bd839c4093b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
